# Generated by Django 5.2.11 on 2026-03-29 06:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('borrower_cnic', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='CNIC must be in the format: 42101-1234567-1', regex='^\\d{5}-\\d{7}-\\d{1}$')])),
                ('borrower_phone', models.CharField(max_length=15)),
                ('borrower_email', models.EmailField(max_length=254)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_deposit_returned', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.book')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
