# Generated by Django 5.2.11 on 2026-03-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bookissue_damage_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='damage_notes',
            field=models.TextField(blank=True, help_text='Describe the damage observed', null=True),
        ),
    ]
